export const customOrder = [
  // Troops
  'Barbarian',
  'Archer',
  'Goblin',
  'Giant',
  'Wall Breaker',
  'Balloon',
  'Wizard',
  'Healer',
  'Dragon',
  'P.E.K.K.A',
  'Minion',
  'Hog Rider',
  'Valkyrie',
  'Golem',
  'Witch',
  'Lava Hound',
  'Bowler',
  'Baby Dragon',
  'Miner',
  'Yeti',
  'Ice Golem',
  'Electro Dragon',
  'Dragon Rider',
  'Headhunter',
  'Electro Titan',
  'Apprentice Warden',
  'Root Rider',
  'Druid',

  // Super troops
  'Super Barbarian',
  'Super Archer',
  'Super Wall Breaker',
  'Super Giant',
  'Sneaky Goblin',
  'Super Miner',
  'Rocket Balloon',
  'Inferno Dragon',
  'Super Valkyrie',
  'Super Witch',
  'Ice Hound',
  'Super Bowler',
  'Super Dragon',
  'Super Wizard',
  'Super Minion',
  'Super Hog Rider',

  // Builder base troops
  'Raged Barbarian',
  'Sneaky Archer',
  'Beta Minion',
  'Boxer Giant',
  'Bomber',
  'Power P.E.K.K.A',
  'Cannon Cart',
  'Drop Ship',
  'Baby Dragon',
  'Night Witch',
  'Hog Glider',
  'Electrofire Wizard',

  // Siege Machines
  'Wall Wrecker',
  'Battle Blimp',
  'Stone Slammer',
  'Siege Barracks',
  'Log Launcher',
  'Flame Flinger',
  'Battle Drill',

  // Pets
  'L.A.S.S.I',
  'Mighty Yak',
  'Electro Owl',
  'Unicorn',
  'Phoenix',
  'Poison Lizard',
  'Diggy',
  'Frosty',
  'Spirit Fox',
  'Angry Jelly',
];
